In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [3]:
data = pd.read_csv("C:/fashion-dataset/styles.csv")

In [5]:
data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44446 entries, 0 to 44445
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  44446 non-null  int64
 1   gender              44446 non-null  object
 2   masterCategory      44446 non-null  object
 3   subCategory         44446 non-null  object
 4   articleType         44446 non-null  object
 5   baseColour          44431 non-null  object
 6   season              44425 non-null  object
 7   year                44445 non-null  float64
 8   usage               44129 non-null  object
 9   productDisplayName  44439 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 3.4+ MB

In [9]:
new_data = data.drop(['year', 'productDisplayName'], axis=1)

In [11]:
new_data = new_data.dropna()

In [13]:
new_data.shape

(44101, 8)

In [15]:
new_data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,usage
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,Casual
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,Casual
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,Casual
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,Casual
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,Casual

In [17]:
new_data.to_csv('new_style.csv', index=False)

In [19]:
new_data.gender.value_counts()

gender
Men       22127
Women     18360
Unisex     2129
Boys        830
Girls       655
Name: count, dtype: int64

In [21]:
gender_translation_syrian = {
    'Men': 'رجالي',
    'Women': 'نسواني',
    'Unisex': 'للجنسين',
    'Boys': 'ولادي',
    'Girls': 'بناتي'
}

new_data['gender'] = new_data['gender'].map(gender_translation_syrian)

In [23]:
new_data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,usage
0,15970,رجالي,Apparel,Topwear,Shirts,Navy Blue,Fall,Casual
1,39386,رجالي,Apparel,Bottomwear,Jeans,Blue,Summer,Casual
2,59263,نسواني,Accessories,Watches,Watches,Silver,Winter,Casual
3,21379,رجالي,Apparel,Bottomwear,Track Pants,Black,Fall,Casual
4,53759,رجالي,Apparel,Topwear,Tshirts,Grey,Summer,Casual

In [25]:
new_data.masterCategory.value_counts()

masterCategory
Apparel           21369
Accessories       11261
Footwear           9200
Personal Care      2140
Free Items          105
Sporting Goods       25
Home                  1
Name: count, dtype: int64

In [27]:
master_category_translation_syrian = {
    'Apparel': 'تياب',
    'Accessories': 'إكسسوارات',
    'Footwear': 'احذية',
    'Personal Care': 'عناية شخصية',
    'Free Items': 'أغراض ببلاش',
    'Sporting Goods': 'أغراض رياضة',
    'Home': 'للبيت'
}

# remove Home, Free Items, Personal Care, Sporting Goods
categories_to_exclude = ['Home', 'Free Items', 'Personal Care', 'Sporting Goods', 'Footwear', 'Accessories']

# Filter out the unwanted categories
new_data = new_data[~new_data['masterCategory'].isin(categories_to_exclude)]

new_data['masterCategory'] = new_data['masterCategory'].map(master_category_translation_syrian)

In [29]:
new_data.shape

(21369, 8)

In [31]:
new_data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,usage
0,15970,رجالي,تياب,Topwear,Shirts,Navy Blue,Fall,Casual
1,39386,رجالي,تياب,Bottomwear,Jeans,Blue,Summer,Casual
3,21379,رجالي,تياب,Bottomwear,Track Pants,Black,Fall,Casual
4,53759,رجالي,تياب,Topwear,Tshirts,Grey,Summer,Casual
5,1855,رجالي,تياب,Topwear,Tshirts,Grey,Summer,Casual

In [33]:
new_data.subCategory.value_counts()

subCategory
Topwear                     15390
Bottomwear                   2686
Innerwear                    1806
Dress                         478
Loungewear and Nightwear      464
Saree                         427
Apparel Set                   106
Socks                          12
Name: count, dtype: int64

In [35]:
subcategory_translation_syrian = {
    'Topwear': 'تياب قسم علوي',
    'Bottomwear': 'تياب قسم سفلي',
    'Innerwear': 'لباس داخلي',
    'Socks': 'جرابات',
    'Dress': 'فستان',
    'Loungewear and Nightwear': 'بيجامات',
    'Apparel Set': 'طقم تياب',
    'Saree': 'ساري'
}

# Remove Innerwear, Socks
subcategories_to_exclude = ['Innerwear']

new_data = new_data[~new_data['subCategory'].isin(subcategories_to_exclude)]

new_data['subCategory'] = new_data['subCategory'].map(subcategory_translation_syrian)

In [37]:
new_data.shape

(19563, 8)

In [41]:
new_data.articleType.value_counts()

articleType
Tshirts               7068
Shirts                3214
Kurtas                1844
Tops                  1762
Jeans                  603
Shorts                 547
Trousers               530
Dresses                464
Sarees                 427
Track Pants            304
Sweatshirts            285
Sweaters               277
Jackets                258
Kurtis                 234
Tunics                 229
Nightdress             188
Leggings               177
Capris                 175
Night suits            141
Skirts                 128
Dupatta                116
Kurta Sets              94
Lounge Pants            61
Suspenders              40
Patiala                 38
Jeggings                34
Lounge Shorts           34
Stockings               32
Salwar                  32
Churidar                30
Tracksuits              29
Swimwear                17
Bath Robe               17
Jumpsuit                16
Waistcoat               15
Baby Dolls              14
Rompers                 12
Booties                 12
Tights                   9
Blazers                  8
Clothing Set             8
Rain Jacket              7
Salwar and Dupatta       7
Shrug                    6
Nehru Jackets            5
Robe                     4
Lehenga Choli            4
Lounge Tshirts           3
Belts                    3
Suits                    1
Name: count, dtype: int64

In [39]:
article_type_translation_syrian = {
    'Tshirts': 'كنزات',
    'Shirts': 'قمصان',
    'Kurtas': 'كُرتات',
    'Tops': 'توبات',
    'Jeans': 'جينزات',
    'Shorts': 'شورتات',
    'Trousers': 'بناطلين',
    'Dresses': 'فساتين',
    'Sarees': 'ساريات',
    'Track Pants': 'بناطلين رياضة',
    'Sweatshirts': 'كنزات شتوية قطن',
    'Sweaters': 'كنزات صوف',
    'Jackets': 'جاكيتات',
    'Kurtis': 'كُرتيات',
    'Tunics': 'تونيكات',
    'Nightdress': 'قمصان نوم',
    'Leggings': 'ليغنغز',
    'Capris': 'بناطلين كابري',
    'Night suits': 'بيجامات نوم',
    'Skirts': 'تنانير',
    'Dupatta': 'شال هندي',
    'Kurta Sets': 'أطقم كُرتا',
    'Lounge Pants': 'بنطلونات مريحة',
    'Suspenders': 'حمالات بنطلون',
    'Patiala': 'بنطلون باتيالا',
    'Jeggings': 'جينز مطاطي',
    'Lounge Shorts': 'شورتات مريحة',
    'Stockings': 'جوارب طويلة',
    'Salwar': 'سلوار',
    'Churidar': 'بنطلون شرويدر',
    'Tracksuits': 'طقم رياضة',
    'Swimwear': 'مايوهات',
    'Bath Robe': 'روب حمام',
    'Jumpsuit': 'جمبسوت',
    'Waistcoat': 'صدرية',
    'Rompers': 'أفرولات',
    'Booties': 'بواط صغار',
    'Tights': 'ليغينغ',
    'Blazers': 'بليزرات',
    'Clothing Set': 'طقم ملابس',
    'Rain Jacket': 'جاكيت مطري',
    'Salwar and Dupatta': 'سلوار مع طرحة',
    'Shrug': 'شراڤ',
    'Nehru Jackets': 'جاكيتات نهرو',
    'Robe': 'روب',
    'Lehenga Choli': 'طقم هندي',
    'Lounge Tshirts': 'تيشرتات بيت',
    'Belts': 'أحزمة',
    'Suits': 'بدلات'
}

# Apply the mapping
new_data['articleType'] = new_data['articleType'].map(article_type_translation_syrian)

new_data = new_data.dropna(subset=['articleType'])

In [41]:
new_data.shape

(19549, 8)

In [43]:
new_data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,usage
0,15970,رجالي,تياب,تياب قسم علوي,قمصان,Navy Blue,Fall,Casual
1,39386,رجالي,تياب,تياب قسم سفلي,جينزات,Blue,Summer,Casual
3,21379,رجالي,تياب,تياب قسم سفلي,بناطلين رياضة,Black,Fall,Casual
4,53759,رجالي,تياب,تياب قسم علوي,كنزات,Grey,Summer,Casual
5,1855,رجالي,تياب,تياب قسم علوي,كنزات,Grey,Summer,Casual

In [45]:
new_data.baseColour.value_counts()

baseColour
Blue                 3313
Black                2849
White                2479
Grey                 1450
Green                1426
Red                  1318
Navy Blue            1131
Pink                 1002
Purple                954
Yellow                546
Brown                 529
Beige                 314
Orange                308
Maroon                295
Cream                 247
Multi                 239
Olive                 169
Off White             142
Peach                 121
Charcoal              120
Magenta                99
Lavender               87
Grey Melange           69
Mustard                67
Teal                   65
Rust                   51
Khaki                  51
Turquoise Blue         33
Burgundy               17
Sea Green              16
Coffee Brown            8
Tan                     8
Gold                    8
Mauve                   5
Lime Green              4
Nude                    3
Silver                  3
Mushroom Brown          1
Fluorescent Green       1
Taupe                   1
Name: count, dtype: int64

In [47]:
base_colour_translation_syrian = {
    'Black': 'أسود',
    'White': 'أبيض',
    'Blue': 'أزرق',
    'Brown': 'بني',
    'Grey': 'رمادي',
    'Red': 'أحمر',
    'Green': 'أخضر',
    'Pink': 'زهري',
    'Navy Blue': 'كحلي',
    'Purple': 'بنفسجي',
    'Silver': 'فضي',
    'Yellow': 'أصفر',
    'Beige': 'بيج',
    'Gold': 'دهبي',
    'Maroon': 'خمري',
    'Orange': 'برتقالي',
    'Olive': 'زيتي',
    'Multi': 'عدة ألوان',
    'Cream': 'سكري',
    'Steel': 'رمادي معدني',
    'Charcoal': 'رمادي غامق',
    'Peach': 'خوخي',
    'Off White': 'أبيض مائل للسكري',
    'Skin': 'لون البشرة',
    'Lavender': 'لافندر',
    'Grey Melange': 'رمادي مموج',
    'Khaki': 'كاكي',
    'Magenta': 'ماجنتا',
    'Teal': 'تركوازي غامق',
    'Tan': 'أسمر فاتح',
    'Mustard': 'خردلي',
    'Bronze': 'برونزي',
    'Copper': 'نحاسي',
    'Turquoise Blue': 'تركوازي',
    'Rust': 'صدّي',
    'Burgundy': 'نبيذي',
    'Metallic': 'معدني',
    'Coffee Brown': 'بني قهوة',
    'Mauve': 'موف',
    'Rose': 'وردي',
    'Nude': 'لون الجلد',
    'Sea Green': 'أخضر بحري',
    'Mushroom Brown': 'بني فطري',
    'Taupe': 'رمادي بني',
    'Lime Green': 'أخضر ليموني',
    'Fluorescent Green': 'أخضر فاقع'
}

new_data['baseColour'] = new_data['baseColour'].map(base_colour_translation_syrian)

In [49]:
new_data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,usage
0,15970,رجالي,تياب,تياب قسم علوي,قمصان,كحلي,Fall,Casual
1,39386,رجالي,تياب,تياب قسم سفلي,جينزات,أزرق,Summer,Casual
3,21379,رجالي,تياب,تياب قسم سفلي,بناطلين رياضة,أسود,Fall,Casual
4,53759,رجالي,تياب,تياب قسم علوي,كنزات,رمادي,Summer,Casual
5,1855,رجالي,تياب,تياب قسم علوي,كنزات,رمادي,Summer,Casual

In [51]:
new_data.season.value_counts()

season
Summer    11251
Fall       7682
Winter      482
Spring      134
Name: count, dtype: int64

In [53]:
season_translation_syrian = {
    'Summer': 'صيفي',
    'Fall': 'خريفي',
    'Winter': 'شتوي',
    'Spring': 'ربيعي'
}


new_data['season'] = new_data['season'].map(season_translation_syrian)

In [55]:
new_data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,usage
0,15970,رجالي,تياب,تياب قسم علوي,قمصان,كحلي,خريفي,Casual
1,39386,رجالي,تياب,تياب قسم سفلي,جينزات,أزرق,صيفي,Casual
3,21379,رجالي,تياب,تياب قسم سفلي,بناطلين رياضة,أسود,خريفي,Casual
4,53759,رجالي,تياب,تياب قسم علوي,كنزات,رمادي,صيفي,Casual
5,1855,رجالي,تياب,تياب قسم علوي,كنزات,رمادي,صيفي,Casual

In [57]:
new_data.usage.value_counts()

usage
Casual          13801
Ethnic           2960
Sports           1572
Formal           1172
Party              22
Smart Casual       21
Travel              1
Name: count, dtype: int64

In [59]:
usage_translation_syrian = {
    'Casual': 'كاجوال',
    'Sports': 'رياضي',
    'Ethnic': 'تراثي',
    'Formal': 'رسمي',
    'Smart Casual': 'كاجوال مرتب',
    'Party': 'سهرات',
    'Travel': 'للسفر',
}

new_data['usage'] = new_data['usage'].map(usage_translation_syrian)

In [61]:
new_data.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,usage
0,15970,رجالي,تياب,تياب قسم علوي,قمصان,كحلي,خريفي,كاجوال
1,39386,رجالي,تياب,تياب قسم سفلي,جينزات,أزرق,صيفي,كاجوال
3,21379,رجالي,تياب,تياب قسم سفلي,بناطلين رياضة,أسود,خريفي,كاجوال
4,53759,رجالي,تياب,تياب قسم علوي,كنزات,رمادي,صيفي,كاجوال
5,1855,رجالي,تياب,تياب قسم علوي,كنزات,رمادي,صيفي,كاجوال

In [63]:
new_data.to_csv('style_ar.csv', index=False)

In [65]:
new_data.count()

id                19549
gender            19549
masterCategory    19549
subCategory       19549
articleType       19549
baseColour        19549
season            19549
usage             19549
dtype: int64

In [7]:
import os
import pandas as pd

# Load the style IDs from the CSV
csv_path = "C:/fashion-dataset/style_ar.csv"  # change if needed
image_folder = "C:/fashion-dataset/images"     # change if needed

# Read the CSV file
df = pd.read_csv(csv_path)

# Make sure the column name matches the one in your CSV (e.g., 'id')
valid_ids = set(str(id).strip() for id in df['id'])

# Loop through the image files in the folder
for filename in os.listdir(image_folder):
    file_id, ext = os.path.splitext(filename)
    if file_id not in valid_ids:
        # Delete the file
        file_path = os.path.join(image_folder, filename)
        os.remove(file_path)
        print(f"Deleted: {filename}")

print("Cleanup complete.")

Cleanup complete.

In [11]:
df = pd.read_csv(csv_path)
df.count()

id                19549
gender            19549
masterCategory    19549
subCategory       19549
articleType       19549
baseColour        19549
season            19549
usage             19549
dtype: int64

In [15]:
csv_ids = set(str(id).strip() for id in df['id'])

# Get image filenames (without extension)
image_ids = set(os.path.splitext(f)[0] for f in os.listdir(image_folder))

# Find IDs in CSV but not in images folder
missing_images = csv_ids - image_ids

# Print missing IDs
if missing_images:
    print("Missing images for the following IDs:")
    for mid in sorted(missing_images):
        print(mid)
else:
    print("✅ All image files are present.")

Missing images for the following IDs:
12347
39401
39403
39410
39425